package gui.components;

import core.Authom;
import gui.components.drawing.ContentPanel;

import javax.swing.*;

/**
 * The main window of the GUI
 * */
public class MainWindow extends JFrame {

    /**
     * Class constructor
     * */
    public MainWindow() {
        super();
        setJMenuBar(createMenuBar());
        setContentPane(mainPanel);

        addListeners();
    }

    /**
     * Auto generated by Intellij
     * */
    private void createUIComponents() {
        contentPanel = new ContentPanel();
    }

    /**
     * Create a menu bar when clicking with right mouse button
     * */
    private JMenuBar createMenuBar() {
        JMenuBar menuBar = new JMenuBar();
        return menuBar;
    }

    /**
     * Init and add all listeners of the main window
     * */
    private void addListeners() {
        computeButton.addActionListener(e-> startComputation());
    }

    /**
     * Calls the Authom class to compute the authom defined in the gui
     * */
    private void startComputation() {
        String string = computeStringTF.getText();
        if (string == null) {
            return;
        }

        string = string.trim();

        Authom authom = new Authom(contentPanel.getStates(), contentPanel.getAlphabet(),
                contentPanel.getTransitionFunction(), contentPanel.getInitialState(), contentPanel.getFinalStates());

        try {
            boolean result = authom.compute(string);
            JOptionPane.showMessageDialog(this, result, "Result", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bad format for authom", "Result", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private JPanel mainPanel;
    private JTextField computeStringTF;
    private JButton computeButton;

    private ContentPanel contentPanel;
}
